# Generated by Django 4.1.3 on 2022-11-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdir', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officename', models.CharField(max_length=30)),
                ('floor', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Userspc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('pc_username', models.CharField(max_length=6)),
                ('pc_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('model', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=15)),
                ('rebuilded', models.BooleanField(default=False)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartipnav.office')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartipnav.ip')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('model', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=15)),
                ('rebuilded', models.BooleanField(default=False)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartipnav.office')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartipnav.ip')),
                ('reg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartipnav.userspc')),
            ],
        ),
    ]
